#!/bin/sh
set -e
FILE=$1
DIR=$(dirname $FILE)
. $(dirname $0)/setup-env
if ! test -s $DIR/WORKFLOW_UUID ; then
  arvados-cwl-runner --create-workflow $FILE > $DIR/WORKFLOW_UUID
fi
shift
arvados-cwl-runner arvwf:$(cat $DIR/WORKFLOW_UUID) $FILE "$@"
